package com.medikiosk.model.enums;

public enum AuditAction {
    USER_REGISTERED, USER_LOGIN, TOKEN_REFRESHED,
    PATIENT_CREATED, PATIENT_UPDATED, PATIENT_LOOKUP,
    SESSION_CREATED, SESSION_RECOVERED, SESSION_EXPIRED,
    SESSION_ABANDONED, SESSION_SUBMITTED, SESSION_CLEANED
}